# Generated by Django 5.2.6 on 2025-09-26 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo ou razão social do cliente', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='E-mail principal para contato', max_length=254, null=True, unique=True)),
                ('telefone', models.CharField(help_text='Telefone para contato (com DDD)', max_length=20)),
                ('cpf_cnpj', models.CharField(blank=True, help_text='CPF ou CNPJ do cliente', max_length=18, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descrição da despesa (ex: Aluguel)', max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(help_text='Data em que a despesa ocorreu ou foi paga')),
                ('categoria', models.CharField(blank=True, help_text='Ex: Fornecedores, Impostos, Salários', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do produto (ex: Banner em Lona)', max_length=100)),
                ('tipo_precificacao', models.CharField(choices=[('UNICO', 'Preço por Unidade'), ('M2', 'Preço por Metro Quadrado')], default='UNICO', help_text='Define como o preço do produto é calculado', max_length=5)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço por unidade ou por metro quadrado', max_digits=10)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='Em Aberto', help_text='Ex: Em Aberto, Aprovado, Rejeitado', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_producao', models.CharField(default='Aguardando', help_text='Ex: Aguardando Arte, Em Produção, Finalizado', max_length=50)),
                ('status_pagamento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcial'), ('PAGO', 'Pago')], default='PENDENTE', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.cliente')),
                ('orcamento_origem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.orcamento')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('largura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Itens de Pedidos',
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('largura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.orcamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto')),
            ],
            options={
                'verbose_name': 'Item de Orçamento',
                'verbose_name_plural': 'Itens de Orçamentos',
            },
        ),
    ]
