# Generated by Django 5.2.6 on 2025-09-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(blank=True, default=None, max_length=18, null=True, unique=True),
        ),
    ]
