# Generated by Django 5.2.6 on 2025-10-14 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cliente_cpf_cnpj_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
