# Generated by Django 5.2.6 on 2025-10-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_orcamento_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_rastreio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='custo_producao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_producao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_envio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='link_fornecedor',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='previsto_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
