# Generated by Django 5.2.6 on 2025-10-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='Gráfica Cloud Design', max_length=200)),
                ('razao_social', models.CharField(blank=True, max_length=200, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.URLField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('logo_grande_dashboard', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('logo_pequena_dashboard', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('logo_orcamento_pdf', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name_plural': 'Empresa',
            },
        ),
    ]
