# Generated by Django 5.2.6 on 2025-10-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='descricao_customizada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='descricao_customizada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
